version: '2'
services:
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - "38882:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data/:z
        restart: always
    django:
        build: ./django
        container_name: django
        ports:
            - "38881:8000"
        volumes:
            - ./django:/django:z
            - ./static:/static:z
        depends_on:
            - postgres
            - nginx
            - postfix
        restart: always
        # WORKAROUND without sleep() django can't connect to database in time
        #command: sh -c "sleep 5 ; python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && gunicorn taskmngr.wsgi -b 0.0.0.0:8000"

        # DEBUGGING:
        command: sh -c "sleep 5 ; python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        #command: sh -c "while true; do sleep 10; done"
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "38880:8000"
        volumes:
            - ./nginx/config:/etc/nginx/conf.d/:z
            - ./django:/django:z
            - ./static:/static:z
        restart: always
    postfix:
        image: catatnight/postfix
        container_name: postfix
        ports:
            - "38883:25"
        environment:
            - maildomain=mail.example.com
            - smtp_user=user1:password1
        restart: always
