# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "bento/centos-7.2"

  VAGRANT_COMMAND = ARGV[0]
  if VAGRANT_COMMAND == "ssh"
    config.ssh.username = 'user1'
  end

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false    # VB gui when booting the machine
  end

  config.vm.define "taskmngr1" do |taskmngr1|
    taskmngr1.vm.provider "virtualbox" do |vb|
      vb.memory = "3800"
      vb.cpus = 2
    end

    taskmngr1.vm.network "private_network", ip: "192.168.59.2"

    # sample(taskmngr1-scripts)
    taskmngr1.vm.provision "shell", path: "../scripts/hosts.sh"
    taskmngr1.vm.provision "shell", path: "../scripts/taskmngr-common.sh"
    taskmngr1.vm.provision "shell", path: "../scripts/taskmngr1.sh"
    # end-sample
  end

  config.vm.define "taskmngr2" do |taskmngr2|
    taskmngr2.vm.provider "virtualbox" do |vb|
      vb.memory = "1100"
      vb.cpus = 2
    end

    taskmngr2.vm.network "private_network", ip: "192.168.59.3"

    # sample(taskmngr2-scripts)
    taskmngr2.vm.provision "shell", path: "../scripts/hosts.sh"
    taskmngr2.vm.provision "shell", path: "../scripts/taskmngr-common.sh"
    taskmngr2.vm.provision "shell", path: "../scripts/taskmngr2.sh"
    # end-sample
  end
end
