virt-install \
	-n taskmngr1 \
  --import \
	--disk path=centos7-base-img/taskmngr1.qcow2,bus=virtio,size=100 \
	--os-variant=centos7.0 \
	--os-type=Linux \
	--ram=2048 \
	--vcpus=2 \
	--graphics vnc,password=1,port=5900 \
	--network bridge:br0 \
	--boot hd
