# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(editable=False, max_length=20)),
                ('body', models.TextField(max_length=500)),
                ('slug', models.SlugField(editable=False)),
                ('timeframe', models.IntegerField(choices=[(0, 'Now'), (1, 'Later'), (2, 'Someday')], default=0)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='tasks.Category')),
            ],
        ),
    ]
