# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170203_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
