# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_is_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='body',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
