apiVersion: v1
kind: ReplicationController
metadata:
    labels:
        app: taskmngr
    name: taskmngr
spec:
    replicas: 1
    selector:
        app: taskmngr
    template:
        metadata:
            labels:
                app: taskmngr
        spec:
            volumes:
                - name: vol1
                  hostPath:
                      path: /tmp/vol1
            containers:
                - image: postgres
                  name: postgres
                  ports:
                      - containerPort: 5432
                - image: bititanb/taskmngr
                  name: django
                  command: ["/bin/sh"]
                  args: ["-c", "while true; do sleep 5; done"]
                  ports:
                      - containerPort: 8000
                  volumeMounts:
                      - name: vol1
                        mountPath: /tmp/voll1
                - image: nginx
                  name: nginx
                  ports:
                      - containerPort: 8001
